version: '3.9'

services:
  gateway:
    build: ./services/Gateway/Gateway.API
    ports:
      - "5000:80"

  authservice:
    build: ./services/AuthService/AuthService.API

  userservice:
    build: ./services/UserService/UserService.API

  sql:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "YourStrong@Pass123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  redis:
    image: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
